// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "swiftStudent",
    platforms: [
        .iOS("16.0"),
        .macOS("13.0")
    ],
    products: [
        .iOSApplication(
            name: "swiftStudent",
            targets: ["AppModule"],
            bundleIdentifier: "aadil.swiftStudent",
            teamIdentifier: "4U87AGX65M",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .calculator),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        ),
        .library(
            name: "EvacuationEngine",
            targets: ["EvacuationEngine"]
        )
    ],
    targets: [
        .target(
            name: "EvacuationEngine",
            path: "Sources/EvacuationEngine"
        ),
        .executableTarget(
            name: "AppModule",
            dependencies: ["EvacuationEngine"],
            path: ".",
            exclude: ["Sources", "Tests"]
        ),
        .testTarget(
            name: "EvacuationEngineTests",
            dependencies: ["EvacuationEngine"],
            path: "Tests/EvacuationEngineTests"
        )
    ],
    swiftLanguageVersions: [.v6]
)
